### ISSUE TITLE
Does not load on Safari

### ISSUE THREAD

**Issue by h4llow3En** [newsic/newsic#1]

**Comment by Feliix42** [comment]
The problem is caused by a combination of my **uBlock** config and the missing support of Safari for default values in JS functions.

**Comment by h4llow3En** [comment]
I deactivated ublock, didn't worked too

**Comment by Feliix42** [comment]
And Ghostery :D

**Comment by Feliix42** [comment]
![on it](http://i.giphy.com/RTGptCQyfIbqU.gif)

**Comment by tocsinDE** [comment]
Missing ES6 specifications in Safari are fixed in the demo version since.. now. Seems like Safari + [blocker of your choice) has a problem with fetching the "https://geoip.nekudo.com/api" script.

**Comment by tocsinDE** [comment]
Is this issue still relevant, @h4llow3En?

**Comment by h4llow3En** [comment]
No, this was fixed
