### ISSUE TITLE
Not working with videos longer than 1 day

### ISSUE THREAD

**Issue by Feliix42** [newsic/newsic#11]
When I enter the following playlist, which only contains a song with longer than _one day_, I get an internal server error:
```
https://www.youtube.com/playlist?list=PLi2DsMKrEWxWJDf12nSJlUj2w5RitVbFf
```

Think this should be fixed :)

**Comment by tocsinDE** [comment]
Wonderful playlist, thanks for sharing 👍 
Fixed that immediately, was a serious bug indeed.
